trigger:
- main

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: Build
    displayName: 'Build job'
    pool:
      name: testPool
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '3.x'

    - script: dotnet restore
      displayName: 'dotnet restore'

    - script: dotnet build --configuration Release
      displayName: 'dotnet build'

    - script: dotnet test --no-restore --verbosity normal
      displayName: 'dotnet test'

- stage: BuildContainers
  displayName: 'Build Containers'
  jobs:
  - job: BuildContainers
    displayName: 'Build Containers'
    pool:
      name: testPool
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: dockerRegistry
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        Dockerfile: 'Dockerfile'
        repository: shahzeb799/nginx
        tags: |
          0.1
